---
title: "curatedTCGAData_Manuscript"
author: "Marcel Ramos"
date: "January 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE}
suppressPackageStartupMessages({
    library(MultiAssayExperiment)
    library(curatedTCGAData)
    library(TCGAutils)
})
```

Load packages:

```{r, eval = FALSE}
library(MultiAssayExperiment)
library(curatedTCGAData)
library(TCGAutils)
```

## Obtain ACC data from curatedTCGAData:

```{r}
suppressMessages({
    acc <- curatedTCGAData::curatedTCGAData("ACC",
        assays = c("miRNASeqGene", "Mutation", "RNASeq2GeneNorm",
            "CNVSNP", "GISTIC_ThresholdedByGene", "RPPAArray"),
        dry.run = FALSE)
})
mut <- assay(acc[["ACC_Mutation-20160128"]], i = "Variant_Classification")
mut <- ifelse(is.na(mut) | mut == "Silent", 0, 1)
# acc[["ACC_Mutation-20160128"]] <- mut
```

```{r}
library(survival)
Surv(acc$days_to_death, acc$vital_status)
```


```{r}
accsurv <- acc[, complete.cases(acc$days_to_death, acc$vital_status), ]
```

```{r}
suppressPackageStartupMessages({
    library(survminer)
})
fit <- survfit(Surv(days_to_death, vital_status) ~ pathology_N_stage,
    data = colData(accsurv))
ggsurvplot(fit, data = colData(accsurv), risk.table = TRUE)
```

```{r}
profvis::profvis({
    wideacc <- wideFormat(accsurv["EZH2", , c(2,3,5,6)],
        colDataCols = c("vital_status", "days_to_death", "pathology_N_stage"))
})
wideacc$y <- Surv(wideacc$days_to_death, wideacc$vital_status)
head(wideacc)
```

```{r}
coxph(Surv(days_to_death, vital_status) ~
    ACC_RNASeq2GeneNorm.20160128_EZH2 +
        log2(ACC_RNASeq2GeneNorm.20160128_EZH2) + pathology_N_stage,
    data=wideacc)
```

```{r}
subacc <- acc[, , c("ACC_RNASeq2GeneNorm-20160128", "ACC_GISTIC_ThresholdedByGene-20160128")]
subacc <- intersectColumns(subacc)
subacc <- intersectRows(subacc)
subacc.list <- assays(subacc)
subacc.list[[1L]] <- log2(subacc.list[[1L]] + 1)
subacc.list <- lapply(subacc.list, t)
corres <- cor(subacc.list[[1]], subacc.list[[2]])

hist(diag(corres))
```

```{r}
df <- wideFormat(subacc["SNRPB2", , ])
head(df)
```

```{r}
boxplot(ACC_RNASeq2GeneNorm.20160128_SNRPB2 ~
    ACC_GISTIC_ThresholdedByGene.20160128_SNRPB2,
    data = df, varwidth = TRUE, xlab = "GISTIC Relative Copy Number Call",
    ylab = "RNA-seq counts")
```

```{r}
getLoadings <- function(x, ncomp=10, dolog=FALSE, center=TRUE, scale.=TRUE) {
  if (dolog)
    x <- log2(x + 1)
  pc <- prcomp(x, center=center, scale.=scale.)
  t(pc$rotation[, seq_len(ncomp)])
}
```

```{r}
acc2 <- intersectColumns(acc)
accassays <- assays(acc2)

acc2 <- c(acc2,
    rnaseqPCA=getLoadings(accassays[["ACC_RNASeq2GeneNorm-20160128"]], dolog=TRUE),
    mapFrom="ACC_RNASeq2GeneNorm-20160128")

acc2 <- c(acc2,
    gistictPCA=getLoadings(assays(acc2)[["ACC_GISTIC_ThresholdedByGene-20160128"]],
    center=FALSE, scale.=FALSE), mapFrom = "ACC_GISTIC_ThresholdedByGene-20160128")

acc2 <- c(acc2,
    proteinPCA=getLoadings(assays(acc2)[["ACC_RPPAArray-20160128"]]),
    mapFrom="ACC_RPPAArray-20160128")
## fix here
acc2 <- c(acc2,
    mutationsPCA=getLoadings(assays(acc2)[["ACC_Mutation-20160128"]],
        center=FALSE, scale.=FALSE),
    mapFrom="ACC_Mutation-20160128")

acc2 <- c(acc2,
    miRNAPCA=getLoadings(assays(acc2)[["ACC_miRNASeqGene-20160128"]]),
    mapFrom="ACC_miRNASeqGene-20160128")
```

```{r}
acc3 <- acc2[, , grepl("PCA", names(acc2))]
experiments(acc3)
```

```{r}
df <- wideFormat(acc3)[, -1]
mycors <- cor(as.matrix(df))
mycors <- abs(mycors)
diag(mycors) <- NA
```

```{r}
has.high.cor <- apply(mycors, 2, max, na.rm=TRUE) > 0.5
mycors <- mycors[has.high.cor, has.high.cor]
pheatmap::pheatmap(mycors)
```

