---
title: "GSEA PanCan"
author: "Waldron Lab"
date: "March 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE}
suppressPackageStartupMessages({
    library(MultiAssayExperiment)
    library(curatedTCGAData)
    library(TCGAutils)
    library(GSEABenchmarkeR)
    library(BiocParallel)
})
```

Load packages:

```{r, eval = FALSE}
library(MultiAssayExperiment)
library(curatedTCGAData)
library(TCGAutils)
library(GSEABenchmarkeR)
library(BiocParallel)
```

## Obtain ACC data from curatedTCGAData:

```{r}
data("diseaseCodes")
head(avail <- diseaseCodes[
    diseaseCodes[["Available"]] == "Yes", "Study.Abbreviation"])
```

```{r}
rnacomp <- curatedTCGAData("*", "RNASeq2*", FALSE)
sampleTables(rnacomp)

tumnorm <- splitAssays(rnacomp, c("01", "11"))

okCodes <- vapply(
    strsplit(names(which(
        vapply(sampleTables(rnacomp),
            function(x) {
            all(c("01", "11") %in% names(x))
            },
            logical(1L)))),
        "_"),
    `[`,
    character(1L),
    1L
)

rnacomp2 <- curatedTCGAData(okCodes, "RNASeq2*", FALSE)

selects <- TCGAsampleSelect(colnames(rnacomp2), c("01", "11"))

rnacomp3 <- rnacomp2[, selects]
enoughNorm <- vapply(sampleTables(rnacomp3),
    function(samp) { samp["11"] > 10L }, logical(1L))

rnacomp4 <- rnacomp3[, , enoughNorm]
sampleTables(rnacomp4)
tlogic <- TCGAsampleSelect(colnames(rnacomp4), "01")
sampIndx <- IntegerList(lapply(tlogic, ifelse, 1L, 0L))

naks <- mendoapply(function(x, y) {
    colData(x)[["GROUP"]] <- y
    x
}, x = experiments(rnacomp4), y = sampIndx)

rnacomp5 <- BiocGenerics:::replaceSlots(rnacomp4,
    ExperimentList = naks,
    check = FALSE)

table(rnacomp5[[1L]]$GROUP)
matchlist <- lapply(setNames(seq_along(rnacomp5), names(rnacomp5)),
    function(idx) {
        as(splitAssays(rnacomp5[, , idx]), "MatchedAssayExperiment")
    }
)
newEXPS <- ExperimentList(
    lapply(matchlist, function(expr) {
        do.call(cbind, experiments(expr))
    })
)

rnacomp6 <- BiocGenerics:::replaceSlots(rnacomp5,
    ExperimentList = newEXPS,
    check = FALSE
)
```

