---
title: "OncoPrint Figure"
author: "Waldron Lab"
date: "July 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Load packages:

```{r,results="hide",include=TRUE,message=FALSE,warning=FALSE}
library(MultiAssayExperiment)
library(curatedTCGAData)
library(TCGAutils)
library(ComplexHeatmap)
library(RColorBrewer)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)
library(GenomeInfoDb)
```

# PANCAN Mutations

```{r,results="hide",include=TRUE,message=FALSE,warning=FALSE}
pancanmut <- curatedTCGAData("*", "Mutation", FALSE)
sampleTables(pancanmut)
pancanmut <- TCGAprimaryTumors(pancanmut)

datafolder <- "~/data"
save(pancanmut, file = file.path(datafolder, "primarypancanmutations.rda"))
load(file.path(datafolder, "primarypancanmutations.rda"))
```

```{r}
mutnames <-
    grep(glob2rx("*_Mutation-*"), names(pancanmut), value = TRUE)
## 32 types of cancer MESO does not have a mutation dataset?

mutlist <- experiments(pancanmut)

mutlist <- lapply(mutlist, function(mutassay) {
    if (all(genome(mutassay) == "19"))
        genome(mutassay) <- paste0("hg", genome(mutassay))
    else
        genome(mutassay) <- TCGAutils::translateBuild(genome(mutassay))

    seqlevelsStyle(mutassay) <- "UCSC"
    rownames(mutassay) <- mcols(mutassay)$Hugo_Symbol
    somaticnonsilent <- mcols(mutassay)$Mutation_Status == "Somatic" &
        mcols(mutassay)$Variant_Classification != "Silent"
    mutassay <- mutassay[somaticnonsilent, ]

    Variants <- mcols(mutassay)$Variant_Classification
    Variants <- gsub("_", " ", Variants)
    Variants <- ifelse(Variants == "R", "RNA", Variants)
    mcols(mutassay)$Variant_Classification <- Variants

    mutassay
})
```

```{r}
muttable <- table(unlist(
    lapply(mutlist, function(x) mcols(x)$Variant_Classification)
))
varikeep <- muttable / sum(muttable) > 0.001
cbind.data.frame(muttable, keep = varikeep, row.names = NULL)
validvariants <- names(muttable)[varikeep]
validvariants <- setNames(validvariants, validvariants)
save(validvariants, file = file.path(datafolder, "validvariants.rda"))
```

LiftOver for Hg18 genomes

```{r}
library(BiocFileCache)
lifturl <-
"http://hgdownload.cse.ucsc.edu/goldenpath/hg18/liftOver/hg18ToHg19.over.chain.gz"
bfc <- BiocFileCache()
qfile <- bfcquery(bfc, "18to19chain", exact = TRUE)[["rpath"]]
cfile <-
if (length(qfile) && file.exists(qfile)) {
    bfcquery(bfc, "18to19chain", exact = TRUE)[["rpath"]]
} else {
    bfcadd(bfc, "18to19chain", lifturl)
}
chainfile <- file.path(tempdir(), gsub("\\.gz", "", basename(cfile)))
R.utils::gunzip(cfile, destname = chainfile, remove = FALSE)
chain <- suppressMessages(
    rtracklayer::import.chain(chainfile)
)

mutlift <- lapply(mutlist, function(mutassay) {
    if (all(genome(mutassay) == "hg18")) {
        ranges19 <- rtracklayer::liftOver(rowRanges(mutassay), chain)
        mutassay <- mutassay[as.logical(lengths(ranges19))]
        rowRanges(mutassay) <- unlist(ranges19)
        genome(mutassay) <- rep("hg19", length(genome(mutassay)))
    }
    seqlevelsStyle(mutassay) <- "NCBI"
    mutassay
})
```

```{r}
library(TxDb.Hsapiens.UCSC.hg18.knownGene)
gn18 <- genes(TxDb.Hsapiens.UCSC.hg18.knownGene)
gn18 <- keepStandardChromosomes(granges(gn18), pruning.mode="coarse")
seqlevelsStyle(gn18) <- "NCBI"
names(gn18) <- AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db, names(gn18),
    keytype = "ENTREZID", column = "SYMBOL")
gn18 <- sort(gn18)
gn18 <- unstrand(gn18)

library(TxDb.Hsapiens.UCSC.hg19.knownGene)
gn19 <- genes(TxDb.Hsapiens.UCSC.hg19.knownGene)
gn19 <- keepStandardChromosomes(granges(gn19), pruning.mode="coarse")
seqlevelsStyle(gn19) <- "NCBI"
names(gn19) <- AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db, names(gn19),
    keytype = "ENTREZID", column = "SYMBOL")
gn19 <- sort(gn19)
gn19 <- unstrand(gn19)

mutlist2 <- lapply(mutlist, function(ragex) {
    rowRanges(ragex) <- unstrand(rowRanges(ragex))
    seqlevelsStyle(ragex) <- "NCBI"
    ragex
})

## combine all cancers

variant_fun <- function(scores, ranges, qranges) {
    as.numeric(any(scores != "Silent"))
}

mut3 <- lapply(mutlist2, function(mutassay) {
    gen <- unique(genome(mutassay))

    if (identical(gen, "hg19"))
        gn <- gn19
    else if (identical(gen, "hg18"))
        gn <- gn18

    resov <- qreduceAssay(mutassay, gn, variant_fun, "Variant_Classification",
        background = 0)
    rownames(resov) <- names(gn)
    resov[!is.na(rownames(resov)), ]
})

allgenes <- Reduce(intersect, lapply(mut3, rownames))

genomut <- vapply(mutlist2, function(x) unique(genome(x)), character(1))

mut4 <- lapply(mut3, function(mutmat) {
    mutmat[allgenes, ]
})

save(mut4, file = file.path(datafolder, "mutationspancan.rda"))
load(file.path(datafolder, "mutationspancan.rda"))

mut18 <- mut4[genomut == "hg18"]
mut19 <- mut4[genomut == "hg19"]

mut18full <- do.call(cbind.data.frame, mut18)
mut19full <- do.call(cbind.data.frame, mut19)

tot18 <- rowSums(mut18full)
tot19 <- rowSums(mut19full)

allgenes <- union(names(tot18), names(tot19))
allsums <- vapply(allgenes, function(g) sum(tot18[g], tot19[g], na.rm = TRUE), double(1L))

topgenes <- head(sort(allsums, decreasing = TRUE), 25)

mutlist18 <- mutlist2[genomut == "hg18"]

mutlist19 <- mutlist2[genomut == "hg19"]



simplify_funs <- lapply(validvariants,
    function(variant) {
        args <- alist(scores =, ranges =, qranges =)
        args <- as.pairlist(args)
        body <- substitute({
            as.numeric(any(S4Vectors::`%in%`(scores, z)))
        }, list(z = variant))
        eval(call("function", args, body))
    }
)


simpres18 <- lapply(simplify_funs, function(variant_fun) {
    lapply(mutlist18, function(mutmat) {
        gn <- gn18[names(gn18) %in% names(topgenes)]
        res <- qreduceAssay(mutmat, gn, variant_fun, "Variant_Classification", background = 0)
        rownames(res) <- names(gn)
        res[!is.na(rownames(res)), ]
    })
})

simps18 <- lapply(simpres18, function(x) do.call(cbind.data.frame, x))

simpres19 <- lapply(simplify_funs, function(variant_fun) {
    lapply(mutlist19, function(mutmat) {
        gn <- gn19[names(gn19) %in% names(topgenes)]
        res <- qreduceAssay(mutmat, gn, variant_fun, "Variant_Classification", background = 0)
        rownames(res) <- names(gn)
        res[!is.na(rownames(res)), ]
    })
})

simps19 <- lapply(simpres19, function(x) do.call(cbind.data.frame, x))

list_mats <- Map(cbind, simps18, simps19)
list_mats2 <- lapply(list_mats, data.matrix)

load("~/data/validvariants.rda")
qualcolors <- RColorBrewer::brewer.pal(n = length(validvariants), 'Set3')
colors <- setNames(qualcolors, validvariants)

mutfuns <- lapply(colors, function(couleur) {
    args <- alist(x =, y =, w =, h =)
    args <- as.pairlist(args)
    body <- substitute({
        grid::grid.rect(x, y, w, h, gp = grid::gpar(fill = z, col = NA))
    }, list(z = couleur))
    eval(call("function", args, body))
})

background <- function(x, y, w, h)
    grid::grid.rect(x, y, w, h,
        gp = grid::gpar(fill = "#FFFFFF", col = "#FFFFFF"))
mutfuns2 <- c(background = background, mutfuns)

save(list_mats2, file = file.path(datafolder, "list_mats2.rda"))
load(file.path(datafolder, "list_mats2.rda"))

ll <- IRanges::LogicalList(lapply(list_mats2, function(y) colSums(y) == 0))
matlog <- do.call(rbind, lapply(ll, unname))
allzero <- apply(matlog, 2, all)
list_mats3 <- lapply(list_mats2, function(x) x[, !allzero])

save(mutfuns2, file = file.path(datafolder, "mutfuns2.rda"))
load(file.path(datafolder, "mutfuns2.rda"))

png("PANCAN_Mutations-oncoprint.png", width = 12, height = 8, units = "in",
    res = 300)
ComplexHeatmap::oncoPrint(
    list_mats3, alter_fun = mutfuns2, col = colors, show_pct = FALSE
)
dev.off()
```

Check across all assays for any mutations

```{r}
summaryfun <- function(scores, ranges, qranges)
    { sum(S4Vectors::`%in%`(scores, vclass)) }
resto <- qreduceAssay(ragex, gn, summaryfun, "Variant_Classification",
    background = 0)
rownames(resto) <- names(gn)
resto <- resto[!is.na(rownames(resto)), ]
tops2 <- head(sort(rowSums(resto), decreasing = TRUE), 25)
```

Create a color palette based on the number of variants

```{r}
# qualcolors <- brewer.pal(n = length(vclass), "Set3")
qualcolors <- colorRampPalette(brewer.pal(n = 12, "Set3"))(26)
colors <- setNames(qualcolors, vclass)
```

```{r}
mutfuns <- lapply(colors, function(couleur) {
    args <- alist(x =, y =, w =, h =)
    args <- as.pairlist(args)
    body <- substitute({
        grid::grid.rect(x, y, w, h, gp = gpar(fill = z, col = NA))
    }, list(z = couleur))
    eval(call("function", args, body))
})

background <- function(x, y, w, h)
    grid.rect(x, y, w, h, gp = gpar(fill = "#FFFFFF", col = "#FFFFFF"))
mutfuns2 <- c(background = background, mutfuns)
```

Using most frequently mutated for each mutation type

```{r}
tops <- ceiling(nrow(updated_mats[[1]]) * 0.0005)
mgenes <- Reduce(union, lapply(updated_mats, function(x)
    names(sort(rowSums(x), decreasing = TRUE)[seq_len(tops)]))
)
ug <- length(unique(mgenes))
upmats2 <- lapply(updated_mats, function(mat) mat[mgenes, ])
```

```{r}
png("Mutations-oncoprint.png", width = 12, height = 8, units = "in", res = 300)
oncoPrint(upmats2, alter_fun = mutfuns2, col = colors, show_pct = FALSE)
dev.off()
```

Using top 25 of all mutations

```{r}
am <- lapply(mutlift, function(mutassay) {
    assay(mutassay[names(topgenes), ], i = "Variant_Classification")
})
ammo <- do.call(cbind, am)

oncoPrint(ammo, alter_fun = mutfuns2, col = colors, show_pct = FALSE)
```



